version: "3.8"
services:
  db:
    image: mariadb
    ports:
      - ${DATABASE_PORT}:3306
    restart: always
    volumes:
      - db-data:/var/lib/mysql/data
    environment:
      MARIADB_ALLOW_EMPTY_ROOT_PASSWORD: "yes"
      MARIADB_DATABASE: ${DATABASE_NAME}
      MARIADB_USER: ${DATABASE_USERNAME}
      MARIADB_PASSWORD: ${DATABASE_PASSWORD}
  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
volumes:
  db-data:
